name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      
      - name: Install ESLint
        run: npm install eslint
      
      - name: Run ESLint
        run: npx eslint . # This will lint all files according to the new config
      
      - name: Run OWASP ZAP
        run: |
          docker run -t owasp/zap2docker-stable zap-baseline.py -t http://localhost:8000 -r zap_report.html
